### ISSUE TITLE
Not clear what to download

### ISSUE THREAD

**Issue by shreevatsa** [e-kato/macuim#2]
Looks like the "Downloads" section from Sourceforge has not been (cannot be?) migrated from Google Code. That is, unlike https://code.google.com/p/macuim/downloads/list which shows several .dmg files to download, it's not clear from https://github.com/e-kato/macuim/ what to download. (For now I just downloaded the dmg from code.google.com, but worried about what will happen once it's shut down.)

**Comment by e-kato** [comment]
Please download dmg from release tab on github (https://github.com/e-kato/macuim/releases).

**Comment by shreevatsa** [comment]
Ah I had missed noticing that tab, thanks.
