### ISSUE TITLE
Can't build uim-mozc with mozc-2.17.2106.102 

### ISSUE THREAD

**Issue by ghost** [e-kato/macuim#3]
We can't build uim-mozc with mozc-2.17.2106.102.
Mozc did "Protobuf file location refactoring", and fcitx-mozc followed it.
https://code.google.com/p/fcitx/issues/detail?id=755

I got a diff of fcitx-mozc and modified it for uim-mozc.
It works for me.

uim/key_translator.h
-#include "session/commands.pb.h"
+#include "protocol/commands.pb.h"

uim/mozc.cc
-#include "config/config.pb.h"
-#include "session/commands.pb.h"
+#include "protocol/config.pb.h"
+#include "protocol/commands.pb.h"

uim/uim.gyp
-'../../session/session_base.gyp:session_protocol',
+'../../protocol/protocol.gyp:commands_proto',

**Comment by e-kato** [comment]
Thanks! Patch applied.
