### ISSUE TITLE
OS X El Capitan で help window がまっ黒に

### ISSUE THREAD

**Issue by kozo2** [e-kato/macuim#5]
添付画像のようにhelp windowがまっ黒になるように思われました。

<img width="1286" alt="screenshot 2015-10-03 05 17 24" src="https://cloud.githubusercontent.com/assets/12192/10256932/52f86902-698f-11e5-8993-2b9209212fba.png">

環境は
- OS X El Capitan
- MacUIM 0.6.16-2

で

MacUIMでIMはTUT-Code(でT-Code)のみ使っています。
Applicationとしてはgoogle chromeとTextEdit上で確認しました。

**Comment by kozo2** [comment]
申し訳ありません。rebootを行うとこの症状が出なくなりました。
closeさせていただきます。

**Comment by kozo2** [comment]
再現方法がわからないのですが再び症状が現れるようになったためとりあえずreopenさせていただきます。

**Comment by e-kato** [comment]
ありがとうございます。とりあえず /Library/Input Methods/MacUIM.app を最新の Xcode で rebuild してみました。全体は真っ黒にはならなくなったようです (候補数の部分がまだ黒いですが)。時間があれば、ソースコードを治したいと思いますが…
https://github.com/e-kato/macuim/releases/download/v0.6.16.2.1/MacUIM.app.tar.gz

**Comment by dspaudio** [comment]
https://github.com/e-kato/macuim/releases/download/v0.6.16.2.1/MacUIM.app.tar.gz
このリンクでダウンロードしたら、ファイルのサイズが片端です。もしかして、よろしければ再アップロードしていただけませんか。ありがとうございます。

**Comment by e-kato** [comment]
こちらで今ダウンロードしたところ問題なかったので、後ほどもう一度試してみてください。

**Comment by dspaudio** [comment]
正常に解凍できません。ファイルのサイズが177KBでしたので以前のリリースのサイズより大きく足りないです。

**Comment by e-kato** [comment]
md5sum が 86a8f7ef90ebe12065fc190c3c2afb87 なら OK です。tar xvf MacUIM.app.tar.gz で展開できます。ちなみにこれは、/Library/Input/MacUIM.app しか含まれていませんので 177KB と小さいですよ。

**Comment by dspaudio** [comment]
あー。そうですね。何かおかしかったと思いました。ありがとうございます。

**Comment by e-kato** [comment]
何時頃の OS X El Capitan のアップデートからか古いバイナリでもこの現象が起きにくくなったようなので、特に新しい MacUIM.app に入れ替える必要はなくて、MacUIM 0.6.16-2 の dmg のままで問題ないと思います (追記、やはり古いビルドだと再現するようでした…入れ替えてご利用ください)。
