### ISSUE TITLE
uim-mozc build fails on mozc-2.23.2815.102

### ISSUE THREAD

**Issue by tomcat14d** [e-kato/macuim#8]
<pre>
In file included from ../../unix/uim/key_translator.cc:31:
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/unix/uim/key_translator.h:65:11: error: no template named 'map'; did you mean 'std::map'?
  typedef map<unsigned int, commands::KeyEvent::ModifierKey> ModifierKeyMap;
          ^~~
          std::map
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_multimap.h:69:11: note: 'std::map' declared here
    class map;
          ^
In file included from ../../unix/uim/key_translator.cc:31:
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/unix/uim/key_translator.h:66:11: error: no template named 'map'; did you mean 'std::map'?
  typedef map<unsigned int, pair<string, string> > KanaMap;
          ^~~
          std::map
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_multimap.h:69:11: note: 'std::map' declared here
    class map;
          ^
In file included from ../../unix/uim/key_translator.cc:31:
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/unix/uim/key_translator.h:66:29: error: no template named 'pair'; did you mean '__gnu_cxx::pair'?
  typedef map<unsigned int, pair<string, string> > KanaMap;
                            ^~~~
                            __gnu_cxx::pair
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/ext/hash_map:73:14: note: '__gnu_cxx::pair' declared here
  using std::pair;
             ^
../../unix/uim/key_translator.cc:371:35: error: use of undeclared identifier 'make_pair'; did you mean 'std::make_pair'?
    CHECK(special_key_map_.insert(make_pair(special_key_map[i].from,
                                  ^~~~~~~~~
                                  std::make_pair
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/base/logging.h:194:4: note: expanded from macro 'CHECK'
  (condition) ? (void) 0 : \
   ^
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:519:5: note: 'std::make_pair' declared here
    make_pair(_T1&& __x, _T2&& __y)
    ^
../../unix/uim/key_translator.cc:375:36: error: use of undeclared identifier 'make_pair'; did you mean 'std::make_pair'?
    CHECK(modifier_key_map_.insert(make_pair(modifier_key_map[i].from,
                                   ^~~~~~~~~
                                   std::make_pair
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/base/logging.h:194:4: note: expanded from macro 'CHECK'
  (condition) ? (void) 0 : \
   ^
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:519:5: note: 'std::make_pair' declared here
    make_pair(_T1&& __x, _T2&& __y)
    ^
../../unix/uim/key_translator.cc:379:37: error: use of undeclared identifier 'make_pair'; did you mean 'std::make_pair'?
    CHECK(modifier_mask_map_.insert(make_pair(modifier_mask_map[i].from,
                                    ^~~~~~~~~
                                    std::make_pair
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/base/logging.h:194:4: note: expanded from macro 'CHECK'
  (condition) ? (void) 0 : \
   ^
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:519:5: note: 'std::make_pair' declared here
    make_pair(_T1&& __x, _T2&& __y)
    ^
../../unix/uim/key_translator.cc:384:40: error: use of undeclared identifier 'make_pair'; did you mean 'std::make_pair'?
        make_pair(kana_map_jp[i].code, make_pair(
                                       ^~~~~~~~~
                                       std::make_pair
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/base/logging.h:194:4: note: expanded from macro 'CHECK'
  (condition) ? (void) 0 : \
   ^
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:519:5: note: 'std::make_pair' declared here
    make_pair(_T1&& __x, _T2&& __y)
    ^
../../unix/uim/key_translator.cc:389:40: error: use of undeclared identifier 'make_pair'; did you mean 'std::make_pair'?
        make_pair(kana_map_us[i].code, make_pair(
                                       ^~~~~~~~~
                                       std::make_pair
/home/tomcat/rpm/BUILD/mozc-2.23.2815.102/src/base/logging.h:194:4: note: expanded from macro 'CHECK'
  (condition) ? (void) 0 : \
   ^
/usr/bin/../lib/gcc/x86_64-mandriva-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:519:5: note: 'std::make_pair' declared here
    make_pair(_T1&& __x, _T2&& __y)
    ^
8 errors generated.
[293/945] ACTION(host) [oss] Generating gen/data_manager/oss/connection.data
ninja: build stopped: subcommand failed.
</pre>

These errors seems to be caused by the mozc team added "std::" prefix.
https://github.com/google/mozc/commit/d5f6e5463c3d0f9cfbe384b8d20b639a0e80c613
https://github.com/google/mozc/commit/37bb71a15cc03b698f6b3f6edcf0e2441dce8544

I created a patch for me, but It seems to work well.
[macuim-mozc-using-namespace-std.patch.tar.gz](https://github.com/e-kato/macuim/files/1783575/macuim-mozc-using-namespace-std.patch.tar.gz)
Please check it.
Thanks.

**Comment by e-kato** [comment]
Thanks. Committed.
